version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
