version: '3'
services:
  backend:
    build: .
    container_name: backend
    restart: unless-stopped
    env_file:
      - ./.env.prod
    ports:
      - 5000:5000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      redis:
        condition: service_healthy
    # networks:
    #   - berrynet
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    # ports:
    #   - 6379:6379
    expose:
      - 6379
    volumes:
      - redis-data:/data
    # networks:
    #   - berrynet
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 2s
      retries: 10

  
volumes:
  redis-data:
  static_volume:
  media_volume:

# networks:
#   berrynet:
#     driver: bridge
